### ISSUE TITLE
Question: how to properly install ign_ros2_control

### ISSUE THREAD

**Issue by vfdev-5** [AndrejOrsula/panda_ign_moveit2#12]
Hi @AndrejOrsula, thanks for the repository. I'm trying to check how description works with ignition and faces dependencies issue.
Following your readme we need to build "ign_ros2_control":

> Build a version based on the selected combination of ROS 2 release and Ignition version

I'm using ROS2 Galactic and ignition fortress, I was checking out https://github.com/ignitionrobotics/ign_ros2_control/tree/ahcorde/galactic/ign_ros2_control branch and could build the workspace with ign_ros2_control and panda_ign_moveit2
However sourcing `install/setup.bash`, I see `not found: "/ws/ros2_ws/install/share/ignition_ros2_control/local_setup.bash"` and executing:
```bash
ros2 launch panda_description view_ign.launch.py
```
> 
```
Captured stderr output: error: package not found: "package 'panda_moveit_config' not found, searching: ['/ws/ros2_ws/install', '/opt/ros/galactic', ]"
when processing file: /ws/ros2_ws/install/share/panda_description/urdf/panda.urdf.xacro
```

Looks like missing `ignition_ros2_control/local_setup.bash` failed to source panda_ign_moveit2.

Any advices on how to make everything work, please ? Thank

EDIT:

without installing at all `ign-ros2-control` and executing view_ign.launch.py, I see `[Err] [SystemLoader.cc:66] Failed to load system plugin [ignition_ros2_control-system] : couldn't find shared library.` and gazebo shows the arm.

**Comment by AndrejOrsula** [comment]
Hello @vfdev-5 ,

> ```bash
> Captured stderr output: error: package not found: "package 'panda_moveit_config' not found, searching: ['/ws/ros2_ws/install', '/opt/ros/galactic', ]"
> when processing file: /ws/ros2_ws/install/share/panda_description/urdf/panda.urdf.xacro
> ```

It is quite strange that `panda_moveit_config` cannot be found when processing xacro from `panda_description`, as they are both part of the same repository (and same build). Both `ros2 pkg prefix --share panda_description` and `ros2 pkg prefix --share panda_moveit_config` should point to the same install share. When building with `colcon`, is there a chance that there was some build error or the package itself was skipped altogether?


> However sourcing `install/setup.bash`, I see `not found: "/ws/ros2_ws/install/share/ignition_ros2_control/local_setup.bash"` ...
> ...
> Looks like missing `ignition_ros2_control/local_setup.bash` failed to source `panda_ign_moveit2`.

I have not experience this issue yet. However, I feel like this suggests that there is something broken in the build of your workspace. More specifically, an error when building `ignition_ros2_control`, e.g. unset `IGNITION_VERSION` which would lead to missing `ignition` dependencies (just a guess).

It is also very strange that missing `ignition_ros2_control/local_setup.bash` would allow `panda_description` to be sourced while `panda_moveit_config` is not.

---

> without installing at all `ign-ros2-control` and executing `view_ign.launch.py`, I see `[Err] [SystemLoader.cc:66] Failed to load > system plugin [ignition_ros2_control-system] : couldn't find shared library.` and gazebo shows the arm.

Yes, that is to be expected. If you don't want that to happen, you could set [`ros2_control` arg in xacro2sdf.bash](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/c65a557f13e46e6ddeef6a5caddfecefb3ef6df7/panda_description/scripts/xacro2sdf.bash#L15) to `false` and execute it. However, the arm would then be without any control and just flop over to the ground.

---

I am currently using [AndrejOrsula/ign_ros2_control:fortress_rolling](https://github.com/AndrejOrsula/ign_ros2_control/tree/fortress_rolling). I have not tried to use [ignitionrobotics/ign_ros2_control:ahcorde/galactic/ign_ros2_control](https://github.com/ignitionrobotics/ign_ros2_control/tree/ahcorde/galactic/ign_ros2_control) yet, but I will give it a try now and let you know if I see any issues with it.

---

When building something new or developing, I generally use a separate workspace for each package (or a small group of related packages) to isolate possible problem. To source everything, I usually place `source /opt/ros/${ROS_DISTRO}/setup.bash` followed by `source */install//local_setup.bash` into a custom setup script (which can then be used in `~/.bashrc`). I don't know whether it's the proper way of doing things, but it might help to isolate potential origin of issue.

**Comment by vfdev-5** [comment]
Thanks a lot for the reply @AndrejOrsula !

Yes, as you suggested the main issue actually is that I couldn't build `ign_ros2_control` plugin library. Colcon does not show clearly (in red) in the end that something is wrong and I thought that everything is OK. 

Looks like debian packages for `ros2_control` (`ros-galactic-ros2-control`) for galactic are somehow old and https://github.com/ignitionrobotics/ign_ros2_control/tree/ahcorde/galactic/ign_ros2_control assumes a newer api and thus shared plugin `libignition_ros2_control-system.so` build is failed.

I think my issue with `panda_moveit_config` is related to missing deps like `ros-galactic-moveit ros-galactic-moveit-servo`.

I close the issue as unrelated to your work. Thanks again for detailed analysis and hints

**Comment by AndrejOrsula** [comment]
Just a follow-up. I tested [ignitionrobotics/ign_ros2_control:ahcorde/galactic/ign_ros2_control](https://github.com/ignitionrobotics/ign_ros2_control/tree/ahcorde/galactic/ign_ros2_control), and it works fine on `rolling` (should/will work fine on `galactic` too).

---

Regarding missing `moveit`/`moveit_servo`, they are both listed under [panda_moveit_config/package.xml#L20-L21](https://github.com/AndrejOrsula/panda_ign_moveit2/blob/c65a557f13e46e6ddeef6a5caddfecefb3ef6df7/panda_moveit_config/package.xml#L20-L21). If they do not get installed through `rosdep install`, then there is some bug.

---

Below are the direct dependencies that I am currently using:
- `ros2_control` - [1.3.0](https://github.com/ros-controls/ros2_control/releases/tag/1.3.0)
- `ros2_controller` - [AndrejOrsula/ros2_controllers:jtc_effort](https://github.com/AndrejOrsula/ros2_controllers/tree/jtc_effort)
  - Needed for effort-only command interface, which is currently the default in the examples as both `position` and `velocity` bypass the physics
  - not my commits
- `ignition_ros2_control` - Either [AndrejOrsula/ign_ros2_control:fortress_rolling](https://github.com/AndrejOrsula/ign_ros2_control/tree/fortress_rolling) or [ignitionrobotics/ign_ros2_control:ahcorde/galactic/ign_ros2_control](https://github.com/ignitionrobotics/ign_ros2_control/tree/ahcorde/galactic/ign_ros2_control) work fine as mentioned above
- `moveit2` - [AndrejOrsula/moveit2:ign_sim_time](https://github.com/AndrejOrsula/moveit2/tree/ign_sim_time)
  - Only needed if you want to plan path while the simulation is paused (otherwise it never times out)
  - not my commits

**Comment by vfdev-5** [comment]
Yes, rebuilding from source ros2_control + ign_ros2_control:ahcorde/galactic/ign_ros2_control solves the problem of failing colcon 👍  Thanks for the confirmation!

That's true that moveit/moveit_servo are in package.xml. I just prefered to install everything manually.


A side question on "best-practices", have you tried or are you using a remote large machine for building/executing (even inside a docker container) and a small machine with VNC to visualize Gazebo, RViz etc ?
In my case, using a remote machine and VNC, running both Gazebo and RViz2 make everything freeze :(

**Comment by AndrejOrsula** [comment]
I have not tried running VNC to view a session of Ignition Gazebo client or RViz2 running on another machine. In case both machines are on the same local network, then running Gazebo client or RViz locally on your laptop is probably the easiest (topics via ignition transport or ROS 2). If they are not on the same network then I suppose VPN could be used (I have not tried that)? There are also some projects that provide web browser-based viewers, but I have not looked into them so not sure what are their requirements and how much they support.

Regarding work on a remote machine, I have been running long-duration simulations using Ignition Gazebo inside Docker. However, I never needed to see the client / RViZ - so I was running everything headless. (It was not truly headless because display for Ignition sensors was still required until recently. Now there is support for EGL, so it should work completely headless - although I have not tried it yet.)

I am no expert in this topic though. I think I came across some threads that discuss this on ROS discourse or Gazebo community/answers, so you might find some better answers there.
